### ISSUE TITLE
request for fasta sequences of the mock community

### ISSUE THREAD

**Issue by MafGal** [andreiprodan/mock-sequences#1]
Hello Andrei @andreiprodan ,

Could you share the fasta sequences of the 20 bacterial strains used in your mock samples?
Or where / how I could get those exact sequences?

Thank you in advance,
Mafalda.

**Comment by andreiprodan** [comment]
I've added a fasta file with the ASV sequences (each with the strain taxonomy) and a short description.

**Comment by MafGal** [comment]
Thanks a lot, that's great!
